name: Deploy Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          docker build -t benitaukaegbu/fastapi-app .
          docker tag benitaukaegbu/fastapi-app:latest benitaukaegbu/fastapi-app:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push benitaukaegbu/fastapi-app:latest
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@143.198.76.102 << 'EOF'
            # Pull latest Docker image
            docker pull benitaukaegbu/fastapi-app:latest
            # Stop and remove running container if it exists
            docker ps -q --filter "name=fastapi-container" | grep -q . && docker stop fastapi-container && docker rm fastapi-container || true
            # Run the container on a different port if 8000 is already in use
            if lsof -i :8000; then
              echo "Port 8000 is in use. Running on port 8001 instead."
              docker run -d --name fastapi-container -p 8001:8000 benitaukaegbu/fastapi-app:latest
            else
              docker run -d --name fastapi-container -p 8000:8000 benitaukaegbu/fastapi-app:latest
            fi
          EOF