name: Deploy Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          docker build -t benitaukaegbu/fastapi-app:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push benitaukaegbu/fastapi-app:latest
      - name: Deploy to Server
        run: |
          ssh root@143.198.76.102 << 'EOF'
            docker pull benitaukaegbu/fastapi-app:latest
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker run -d --name fastapi-container -p 8000:8000 benitaukaegbu/fastapi-app:latest
          EOF