name: Deploy FastAPI App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build -t benitaukaegbu/fastapi-app .
          docker tag benitaukaegbu/fastapi-app benitaukaegbu/fastapi-app:latest
          docker push benitaukaegbu/fastapi-app:latest
      - name: Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@143.198.76.102 << 'EOF'
            echo "Pulling latest Docker image..."
            docker pull benitaukaegbu/fastapi-app:latest
            echo "Checking for existing container..."
            if [ "$(docker ps -aq -f name=fastapi-container)" ]; then
              echo "Stopping and removing existing container..."
              docker stop fastapi-container && docker rm fastapi-container
            fi
            echo "Starting new container..."
            docker run -d --name fastapi-container -p 8000:8000 benitaukaegbu/fastapi-app:latest
          EOF